### ISSUE TITLE
Thanks for your project. But ld error?

### ISSUE THREAD

**Issue by bit-rocket** [linyu92/ShadowSOCKClient#1]
Hi, 
  Thanks for write this project, but after I check out and run
`pod install
`
and then cmd+b to build the project, error occurs as follows 
`
ld: library not found for -llibsodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
Could you please help?

**Comment by linyu92** [comment]
The pod file is too old to install. Replace the content below and install again
////////////////////////////////
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
platform :ios, '9.2'
xcodeproj 'ShadowSOCKClient'
target 'ShadowSOCKClient' do
	pod 'libsodium', '~>1.0.3'
	pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
end
